config/routes.rb
Italia::Application.routes.draw do

  devise_for :users

  match 'contato' => 'contato#new', :as => 'contato', :via => :get
  match 'contato' => 'contato#create', :as => 'contato', :via => :post

  resources :parceiros do
    collection do
      get "lista"
    end
  end

  get "inscricao/detalhes"

  get "edital/regulamento"

  resources :eventos do
    collection do
      get "listagem"
    end
  end

  resources :galerias do
    collection do
      get "fotos"
    end
  end

  resources "contato", only: [:new, :create]

  resources :regulamentos

  resources :premios do
    collection do
      get "descricao"
    end
  end

  resources :noticias do
    collection do
      get "lista"
    end

  end

  resources :conteudos

  get "premio/descricao"

  get "home/index"
  root :to => "home#index"

end

app/models/evento.rb
class Evento < ActiveRecord::Base
  extend FriendlyId

  friendly_id :nome

  attr_accessible :data_evento, :nome, :subtitulo, :descricao_evento

  has_many :galerias, class_name: "Galeria", foreign_key: "evento_id"

  # VALIDACOES
  validates_presence_of :data_evento, :nome, :descricao_evento

  # SCOPES
  scope :order_by_data_evento_desc, order("data_evento, id DESC")

  def primeiro_evento
    self.class.first
  end

  def anterior_evento
    self.class.first(conditions: ["id < ?", self.id], order: "data_evento, id DESC")
  end

  def proximo_evento
    self.class.first(conditions: ["id > ?", self.id], order: "data_evento, id DESC")
  end

  def ultimo_evento
    self.class.last
  end


end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.order_by_data_evento_desc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventos }
    end
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    @evento = Evento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/new
  # GET /eventos/new.json
  def new
    @evento = Evento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/1/edit
  def edit
    @evento = Evento.find(params[:id])
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(params[:evento])

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render json: @evento, status: :created, location: @evento }
      else
        format.html { render action: "new" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /eventos/1
  # PUT /eventos/1.json
  def update
    @evento = Evento.find(params[:id])

    respond_to do |format|
      if @evento.update_attributes(params[:evento])
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento = Evento.find(params[:id])
    @evento.destroy

    respond_to do |format|
      format.html { redirect_to eventos_url }
      format.json { head :no_content }
    end
  end

  def listagem
  end

end

app/helpers/eventos_helper.rb
module EventosHelper

  def helper_evento_name(evento_id)
    evento_name = ""
    if evento_id
      evento = Evento.where(:id => evento_id).first
      if evento
        evento_name = evento.nome
      end
    end
    evento_name
  end

  def helper_evento_box(evento_objeto)
    render "eventos/evento_box", evento_box: evento_objeto
  end

  def helper_evento_list_box(evento_list)
    render "eventos/list_eventos_box", evento_lista: evento_list
  end
  
end

app/views/eventos/_evento_box.html.erb
<div class="col-md-4 column">
    <div class="list-group">
      <!--<a href="#" class="list-group-item active"><%= evento_box.nome %></a>-->
      <%= link_to evento_box.nome, evento_box, class: "list-group-item active " %>
      <div class="list-group-item list-group-item-success">
        <%= evento_box.data_evento %>
      </div>
      <% if evento_box.subtitulo %>
          <div class="list-group-item">
            <h4 class="list-group-item-heading">
              <%= evento_box.subtitulo %>
            </h4>
          </div>
      <% end %>
      <div class="list-group-item">
        <span class="badge"><%= evento_box.galerias.size || 0 %></span>
        <%= link_to "Fotos", evento_box %>
      </div>
    </div>
</div>

app/views/eventos/_form.html.erb
<%= simple_form_for(@evento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :subtitulo %>
    <%= f.input :data_evento %>
    <%= f.input :descricao_evento %>
  </div>
  <br/>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-info" %>
  </div>
  <br/>
<% end %>

app/views/eventos/_list_eventos_box.html.erb
<% cont = 0 %>
<% evento_lista.each do |evento| %>

    <% row_open = cont == 0 %>
    <% row_end = cont == 2 %>

    <% if row_open %>
        <div class="row">
    <% end %>

    <%= helper_evento_box(evento) %>

    <% if row_end %>
        </div>
        <% cont = 0 %>
    <% else %>
        <% cont += 1 %>
    <% end %>

<% end %>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to helper_app_btn_title_show, @evento, class: helper_app_btn_icon_show %> |
<%= link_to helper_app_btn_title_back, eventos_path, class: helper_app_btn_icon_back %>

app/views/eventos/index.html.erb
<h1>Listing eventos</h1>

<%= link_to helper_app_btn_title_new, new_evento_path, class: helper_app_btn_icon_new %>
<br/>
<table class="table table-hover table-condensed">
  <thead>
      <tr>
        <th>Nome</th>
        <th>Data evento</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
  </thead>
  <tbody>
      <% @eventos.each do |evento| %>
          <tr>
            <td><%= evento.nome %></td>
            <td><%= evento.data_evento %></td>
            <td><%= link_to '', evento, class: helper_app_btn_icon_show_row, title: helper_app_btn_title_show %></td>
            <td><%= link_to '', edit_evento_path(evento), class: helper_app_btn_icon_edit_row,
                            title: helper_app_btn_title_edit %></td>
            <td><%= link_to '', evento, method: :delete, data: { confirm: 'Are you sure?' },
                            class: helper_app_btn_icon_destroy, title: helper_app_btn_title_destroy %></td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/eventos/listagem.html.erb
<h2>Eventos</h2>
<hr/>
<%= helper_evento_list_box(Evento.order_by_data_evento_desc.all) %>

app/views/eventos/new.html.erb
<h1>New evento</h1>

<%= render 'form' %>

<%= link_to helper_app_btn_title_back, eventos_path, class: helper_app_btn_icon_back %>

app/views/eventos/show.html.erb
<h2><%= @evento.nome %></h2>
<hr/>
<em class="muted">
  <p><%= @evento.subtitulo %></p>
  <p>Data: <%= @evento.data_evento %></p>
</em>
<br/>
<p class="well">
  <% (@evento.descricao_evento || "Nenhuma descrição informada").split("\n").each do |t| %>
      <%= t %><br/>
  <% end %>
</p>

<% galeria_por_evento = Galeria.where_evento_id(@evento.id) %>
<% if galeria_por_evento.size > 0 %>
    <h4>Veja as fotos do evento:</h4>
    <%= helper_galeria_fotos_por_evento(galeria_por_evento) %>
<% end %>

<br/>

<div class="">
  <ul class="pager pagination-lg">

    <% proximo_evento = @evento.proximo_evento %>
    <% anterior_evento = @evento.anterior_evento %>

    <li><%= link_to("Último Evento", @evento.ultimo_evento) if proximo_evento %></li>
    <li><%= link_to("< Próximo Evento", proximo_evento) if proximo_evento %></li>
    <li><%= link_to("Evento Anterior >", anterior_evento) if anterior_evento %></li>
    <li><%= link_to("Primeiro Evento", @evento.primeiro_evento)  if anterior_evento %></li>

  </ul>
</div>

<%= link_to helper_app_btn_title_edit, edit_evento_path(@evento), class: helper_app_btn_icon_edit %> |
<%= link_to helper_app_btn_title_back, eventos_path, class: helper_app_btn_icon_back %>