config/routes.rb
Italia::Application.routes.draw do

  devise_for :users

  match 'contato' => 'contato#new', :as => 'contato', :via => :get
  match 'contato' => 'contato#create', :as => 'contato', :via => :post

  resources :parceiros do
    collection do
      get "lista"
    end
  end

  get "inscricao/detalhes"

  get "edital/regulamento"

  resources :eventos do
    collection do
      get "listagem"
    end
  end

  resources :galerias do
    collection do
      get "fotos"
    end
  end

  resources "contato", only: [:new, :create]

  resources :regulamentos

  resources :premios do
    collection do
      get "descricao"
    end
  end

  resources :noticias do
    collection do
      get "lista"
    end

  end

  resources :conteudos

  get "premio/descricao"

  get "home/index"
  root :to => "home#index"

end

app/models/galeria.rb
class Galeria < ActiveRecord::Base
  attr_accessible :titulo, :file, :evento_id

  belongs_to :evento, class_name: "Evento", foreign_key: :evento_id

  has_attached_file :file, styles: { medium: "300x300>", thumbnail: "100x100" }

  validates_presence_of :evento

  # SCOPES
  scope :where_evento_id, lambda{|evento_id| where("evento_id = ?", evento_id)}

end

app/controllers/galerias_controller.rb
class GaleriasController < ApplicationController
  # GET /galerias
  # GET /galerias.json
  def index
    @galerias = Galeria.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galerias }
    end
  end

  # GET /galerias/1
  # GET /galerias/1.json
  def show
    @galeria = Galeria.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @galeria }
    end
  end

  # GET /galerias/new
  # GET /galerias/new.json
  def new
    @galeria = Galeria.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @galeria }
    end
  end

  # GET /galerias/1/edit
  def edit
    @galeria = Galeria.find(params[:id])
  end

  # POST /galerias
  # POST /galerias.json
  def create
    @galeria = Galeria.new(params[:galeria])

    respond_to do |format|
      if @galeria.save
        format.html { redirect_to @galeria, notice: 'Galeria was successfully created.' }
        format.json { render json: @galeria, status: :created, location: @galeria }
      else
        format.html { render action: "new" }
        format.json { render json: @galeria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galerias/1
  # PUT /galerias/1.json
  def update
    @galeria = Galeria.find(params[:id])

    respond_to do |format|
      if @galeria.update_attributes(params[:galeria])
        format.html { redirect_to @galeria, notice: 'Galeria was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @galeria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galerias/1
  # DELETE /galerias/1.json
  def destroy
    @galeria = Galeria.find(params[:id])
    @galeria.destroy

    respond_to do |format|
      format.html { redirect_to galerias_url }
      format.json { head :no_content }
    end
  end

  def fotos
  end

end

app/helpers/galerias_helper.rb
module GaleriasHelper

  def helper_galeria_fotos_por_evento(galeria_lista)
    render "galerias/galeria_listagem", galeria_lista: galeria_lista
  end

end

app/views/galerias/_form.html.erb
<%= simple_form_for(@galeria, :html => { :multipart => true }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <div class="control-group">
      <%= f.label :evento_id %>
      <div class="controls">
        <%= f.collection_select(:evento_id, Evento.all, :id, :nome, :prompt => "--Selecione--") %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :file %>
      <div class="controls">
        <%= f.file_field :file %>
      </div>
    </div>
  </div>
  <br/>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-info" %>
  </div>
  <br/>
<% end %>

app/views/galerias/_galeria_listagem.html.erb
<%= render_gallery_for galeria_lista %>

app/views/galerias/edit.html.erb
<h1>Editando galeria</h1>

<%= render 'form' %>

<%= link_to helper_app_btn_title_show, @galeria, class: helper_app_btn_icon_show %> |
<%= link_to helper_app_btn_title_back, galerias_path, class: helper_app_btn_icon_back %>

app/views/galerias/fotos.html.erb
<h2>Fotos</h2>
<h4>Selecione o evento:</h4>
<hr/>

<%= helper_galeria_fotos_por_evento(Galeria.all) %>

app/views/galerias/index.html.erb
<h1>Listing galerias</h1>

<%= link_to helper_app_btn_title_new, new_galeria_path, class: helper_app_btn_icon_new %>
<br/>
<table class="table table-hover table-condensed">
  <thead>
      <tr>
        <th>Titulo</th>
        <th>Evento</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
  </thead>
  <tbody>
      <% @galerias.each do |galeria| %>
          <tr>
            <td><%= galeria.titulo %></td>
            <td><%= helper_evento_name(galeria.evento_id) %></td>
            <td><%= link_to '', galeria, class: helper_app_btn_icon_show_row, title: helper_app_btn_title_show %></td>
            <td><%= link_to '', edit_galeria_path(galeria), class: helper_app_btn_icon_edit_row,
                            title: helper_app_btn_title_edit %></td>
            <td><%= link_to '', galeria, method: :delete, data: { confirm: 'Are you sure?' },
                            class: helper_app_btn_icon_destroy, title: helper_app_btn_title_destroy %></td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/galerias/new.html.erb
<h1>New galeria</h1>

<%= render 'form' %>

<%= link_to helper_app_btn_title_back, galerias_path, class: helper_app_btn_icon_back %>

app/views/galerias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @galeria.titulo %>
</p>

<p>
  <b>Foto</b>
  <br/>
  <%= image_tag(@galeria.file.url) %>
</p>
<br/>

<%= link_to helper_app_btn_title_edit, edit_galeria_path(@galeria), class: helper_app_btn_icon_edit %> |
<%= link_to helper_app_btn_title_back, galerias_path, class: helper_app_btn_icon_back %>