config/routes.rb
Italia::Application.routes.draw do

  devise_for :users

  match 'contato' => 'contato#new', :as => 'contato', :via => :get
  match 'contato' => 'contato#create', :as => 'contato', :via => :post

  resources :parceiros do
    collection do
      get "lista"
    end
  end

  get "inscricao/detalhes"

  get "edital/regulamento"

  resources :eventos do
    collection do
      get "listagem"
    end
  end

  resources :galerias do
    collection do
      get "fotos"
    end
  end

  resources "contato", only: [:new, :create]

  resources :regulamentos

  resources :premios do
    collection do
      get "descricao"
    end
  end

  resources :noticias do
    collection do
      get "lista"
    end

  end

  resources :conteudos

  get "premio/descricao"

  get "home/index"
  root :to => "home#index"

end

app/views/layouts/_footer.html.erb
<div class="panel-footer">
  <div class="row clearfix">

    <div class="col-md-4 column">
      <h3>
        Realização
      </h3><img alt="Italia" height="100" width="200"
                src="/assets/logo.png"/>
    </div>

    <div class="col-md-3">
      <h3>
        Apoio
      </h3><img alt="Governo de Minas Gerais" height="100" width="200" src="/assets/governominas-logo.jpg">
    </div>

    <div class="col-md-4 column">
      <h3>Siga-nos</h3>
      <a href="http://www.facebook.com/premiomineiroinovacao" target="_blank"><img src="/assets/icons/facebook.png" width="32" height="32"></a>
      <a href="http://www.twitter.com/premiomineiroinovacao" target="_blank"><img src="/assets/icons/twitter.png" width="32" height="32"></a>
      <a href="http://www.instagram.com/premiomineiroinovacao" target="_blank"><img src="/assets/icons/instagram.png" width="32" height="32"></a>
      <a href="http://www.youtube.com/premiomineiroinovacao" target="_blank"><img src="/assets/icons/youtube.png" width="32" height="32"></a>
    </div>

    <div class="col-md-8">
      <small>
        Copyright © 2014 | Câmara Italiana de MG | Todos os direitos reservados.
      </small>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container header">
    <div class="row clearfix">
          <div class="navbar-collapse" id="navbar1">
            <ul class="nav nav-pills">
              <li><a class="navbar-brand" href="/">HOME</a></li>
              <li><a class="navbar-brand" href="/premios/descricao">PRÊMIOS</a></li>
              <li><a class="navbar-brand" href="/noticias/lista">NOTÍCIAS</a></li>
              <li><a class="navbar-brand" href="/parceiros/lista">PARCEIROS</a></li>
              <li><a class="navbar-brand" href="/galerias/fotos">FOTOS</a></li>
              <li><a class="navbar-brand" href="/contato/new">CONTATOS</a></li>
              <% if user_signed_in? %>
                  <li><%= link_to image_tag('login_white.png', height: '32', width: '32'), destroy_user_session_path, method: :delete, :class => 'navbar-brand' %></li>
              <% else %>
                  <li><%= link_to image_tag('login_black.png', height: '32', width: '32'), new_user_session_path, :class => 'navbar-brand'  %></li>
              <% end %>
            </ul>
          </div>
    </div>
</div>

app/views/layouts/_menu_administracao.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-10 column">
      <ul class="breadcrumb">
        <li>
          <p>Administração >> </p>
        </li>
        <li><%= link_to "Premios", premios_path %> <span class="divider"></span></li>
        <li><%= link_to "Noticias", noticias_path %> <span class="divider"></span></li>
        <li><%= link_to "Eventos", eventos_path %> <span class="divider"></span></li>
        <li><%= link_to "Galerias", galerias_path %> <span class="divider"></span></li>
        <li><%= link_to "Parceiros", parceiros_path %> <span class="divider"></span></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Italia</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="panel panel-default">

  <div class="panel-body">
    <% if user_signed_in? %>
        <div>Logado como <%= current_user.email %></div>
    <% end %>
  </div>

</div>

<div class="container">

  <% if user_signed_in? %>
    <%= helper_app_menu_admin %>
  <% end %>

  <div class="row clearfix">
    <div class="col-md-12 column">
      <%= yield %>
    </div>
  </div>

</div>

<hr/>
<%= render 'layouts/footer' %>

</body>
</html>